# Generated by Django 5.0.3 on 2024-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truthbomb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='truthsocial',
            table='Trump_Truth_Social',
        ),
    ]
